### ISSUE TITLE
DATE Only field adds timezone in forest

### ISSUE THREAD

**Issue by desi** [ForestAdmin/forest-rails#301] opened 2018-12-13 05:07 UTC
## Expected behavior
We currently have a date only field storing to Postgres. When I query that field it has no time associated in the database nor in our rails console. However in Forest it is applying a timezone which is throwing off the date.

Example date: 11/21/1976 
expected: 11/21/1976
actual: 20/11/1976 17:00:00

Due to timezone it is showing the date as Nov 20th. 1976. This is a birthdate and we don't want any associated time.

* Package Version: Forest 2.11.0
* Rails Version: 4.2.10
* Database Dialect: Postgres
* Database Version: 10.6

**Comment by arnaudbesnier** [comment] 2019-01-16 08:10
Hi @desi ,
The current version of the gem does not handle well this type of database column.
This issue is probably a duplicate of this one: https://github.com/ForestAdmin/forest-rails/issues/300

To help us fix this, could you share with us the column type in your Postgres database?

Thank you.

**Comment by arnaudbesnier** [comment] 2019-07-18 16:08
Hi @desi, this should be fixed in the new liana version v3.1.1.

Thanks for your patience.
Feel free to reopen the thread if the issue persists after the update.

**Closed by arnaudbesnier** 2019-07-18 16:08 UTC
Labels: bug
